var starterSub = { "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Closed" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Closed" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [

], 
 "finalRoom": { "number": 1 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 0}; 

 var results = [
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Closed" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Closed" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [

], 
 "finalRoom": { "number": 1 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 0},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Closed" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 2 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 1},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Closed" },
{ "number": "1-3" , "state": "Open" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Closed" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-3" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 3 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 3 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 1},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Open" },
{ "number": "2-5" , "state": "Closed" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-4" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 4 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 4 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 2},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 5 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 2},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Open" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "5-6" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 6 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 6 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 3},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Open" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "5-7" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 7 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 7 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 3},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Open" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "5-8" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 8 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 8 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 3},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Open" },
{ "number": "5-8" , "state": "Closed" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Open" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Closed" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "5-7" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 7 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "7-9" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 9 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 9 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 4},
{ "rooms": [
{ "number": 1 , "state": "Clear" },
{ "number": 2 , "state": "Clear" },
{ "number": 3 , "state": "Clear" },
{ "number": 4 , "state": "Clear" },
{ "number": 5 , "state": "Clear" },
{ "number": 6 , "state": "Clear" },
{ "number": 7 , "state": "Clear" },
{ "number": 8 , "state": "Clear" },
{ "number": 9 , "state": "Clear" },
{ "number": 10 , "state": "Clear" }
], 
 "hatches": [
{ "number": "1-2" , "state": "Open" },
{ "number": "1-3" , "state": "Closed" },
{ "number": "2-3" , "state": "Closed" },
{ "number": "2-4" , "state": "Closed" },
{ "number": "2-5" , "state": "Open" },
{ "number": "3-4" , "state": "Closed" },
{ "number": "4-5" , "state": "Closed" },
{ "number": "5-6" , "state": "Closed" },
{ "number": "5-7" , "state": "Closed" },
{ "number": "5-8" , "state": "Open" },
{ "number": "7-8" , "state": "Closed" },
{ "number": "7-9" , "state": "Closed" },
{ "number": "8-9" , "state": "Closed" },
{ "number": "8-10" , "state": "Open" },
{ "number": "9-10" , "state": "Closed" }
], 
 "actions": [
{ "type": "OpenHatch", "hatch": { "number": "1-2" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 2 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "2-5" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 5 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "5-8" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 8 , "state": "Clear" }, "cost": 0 },
{ "type": "OpenHatch", "hatch": { "number": "8-10" , "state": "Closed" }, "cost": 1 },
{ "type": "Move", "room": { "number": 10 , "state": "Clear" }, "cost": 0 }
], 
 "finalRoom": { "number": 10 , "state": "Clear" }, 
 "startRoom": { "number": 1 , "state": "Clear" }, 
 "totalCost": 4}
];